name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: docker build .

  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Flake8
      uses: TrueBrain/actions-flake8@v1
      with:
        path: mqtt_to_influx

  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up packages
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Black
      run: |
        black -l 120 --check mqtt_to_influx

  check_annotations:
    name: Check Annotations
    needs:
    - docker
    - flake8
    - black
    # not codeql, as that reports its own status

    if: always() && github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - name: Check annotations
      uses: OpenTTD/actions/annotation-check@v2
